name: Fetch buoy data and update Google Sheet

on:
  # 4am, Noon, 4pm US Eastern (EDT = UTC-4 → 08:00, 16:00, 20:00 UTC)
  schedule:
    - cron: "0 8,16,20 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  fetch-and-write:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Use requirements.txt if present, then ensure Google libs are installed
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib gspread requests

      - name: Create Google credentials file
        run: |
          mkdir -p credentials
          cat << 'EOF' > credentials/google-service-account.json
          ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          EOF

      - name: Run fetch and write
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials/google-service-account.json
        run: python fetch_and_write.py
