name: WaveWatchr Unified Run

on:
  workflow_dispatch: {}
  schedule:
    # 4am, 12pm, 4pm ET -> 08,16,20 UTC (adjust if DST changes matter later)
    - cron: "0 8,16,20 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: ${{ secrets.TZ }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create credentials file from secret
        shell: bash
        run: |
          mkdir -p credentials
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > credentials/google-service-account.json

      - name: Create station_config.json from secret
        shell: bash
        run: |
          echo '${{ secrets.STATION_CONFIG_JSON }}' > station_config.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Silence LibreSSL warning if it appears
          pip install "urllib3<2" || true

      - name: Run fetch_and_write.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials/google-service-account.json
        run: |
          python fetch_and_write.py

      - name: Format buoy_data tab
        if: always()
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials/google-service-account.json
        run: |
          python format_sheet.py || true
