name: Fetch buoy data and update Google Sheet

on:
  schedule:
    # 4am, 12pm, 4pm UTC?  Adjust as needed (this is UTC).
    - cron: "0 4,12,16 * * *"
  workflow_dispatch: {}   # <-- enables the Run workflow button

permissions:
  contents: read

concurrency:
  group: fetch-and-write
  cancel-in-progress: true

jobs:
  fetch-and-write:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Google credentials file
        shell: bash
        run: |
          mkdir -p credentials
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > credentials/google-service-account.json

      - name: Run fetch and write
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials/google-service-account.json
        run: python fetch_and_write.py
