name: WaveWatchr • Fetch + Alerts

on:
  schedule:
    # Every 30 minutes
    - cron: "*/30 * * * *"
    # Alert windows at 04:00, 12:00, 16:00 UTC
    - cron: "0 4,12,16 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      # This path is where we'll write the SA key
      GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-sa.json

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Write Google SA credentials
        shell: bash
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          if [ -z "$GOOGLE_SERVICE_ACCOUNT_JSON" ]; then
            echo "❌ Missing repo secret: GOOGLE_SERVICE_ACCOUNT_JSON"
            exit 1
          fi
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > "$GOOGLE_APPLICATION_CREDENTIALS"
          python - <<'PY'
import json, os, sys
p = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
try:
    json.load(open(p))
    print("✅ SA JSON validated:", p)
except Exception as e:
    print("❌ Invalid SA JSON:", e)
    sys.exit(1)
PY

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch & write latest buoy data (every run)
        run: |
          python fetch_and_write.py

      # Alerts: these steps are safe if files are absent (they’ll just skip).
      # Each alert script should handle writing to its own Google Sheet tab.
      - name: Longboard alert (SwP > 13, SwH > 0.7m, SwD 25°–160°)
        if: ${{ hashFiles('alert_longboard.py') != '' }}
        run: |
          python alert_longboard.py

      - name: Shortboard alert (SwP > 13, SwH > 1.6m, SwD 25°–160°)
        if: ${{ hashFiles('alert_shortboard.py') != '' }}
        run: |
          python alert_shortboard.py

      - name: Short period alert (WVHT > 3ft, MWD 25°–160°)
        if: ${{ hashFiles('alert_shortperiod.py') != '' }}
        run: |
          python alert_shortperiod.py
