name: Fetch buoy data and update Google Sheet

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:         # allow manual runs from Actions tab

jobs:
  fetch-and-write:
    runs-on: ubuntu-latest

    env:
      SA_PATH: credentials/google-service-account.json
      # If your script needs these, uncomment and fill in:
      # SHEET_ID: "<your-google-sheet-id>"
      # WORKSHEET_NAME: "<tab name>"

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Google credentials file
        run: |
          mkdir -p credentials
          cat > $SA_PATH <<'EOF'
          ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          EOF

      - name: Run fetch and write
        run: python fetch_and_write.py
